import { addDays, localDay, type Workspace, type Stage } from "./domain";
const companies = [
  ["Juniper Studio", "Creative", "Portland, OR"],
  ["Northstar Electric", "Construction", "Austin, TX"],
  ["Alder & Oak", "Retail", "Denver, CO"],
  ["Goodfield Co.", "Professional services", "Chicago, IL"],
  ["Forma Architecture", "Creative", "Seattle, WA"],
  ["Bluebird Hospitality", "Hospitality", "Nashville, TN"],
  ["Atlas Engineering", "Professional services", "Boston, MA"],
  ["Meadow Collective", "Retail", "Madison, WI"],
  ["Brightside Solar", "Construction", "Phoenix, AZ"],
  ["Paperplane Digital", "Technology", "Brooklyn, NY"],
  ["Sunday Coffee", "Hospitality", "Minneapolis, MN"],
  ["Evergreen Systems", "Technology", "Raleigh, NC"],
];
const people = [
  "Olivia Chen",
  "Marcus Reed",
  "Sophia Patel",
  "James Wilson",
  "Emma Torres",
  "Noah Brooks",
  "Ava Mitchell",
  "Liam Foster",
  "Isabella Park",
  "Ethan Hayes",
  "Mia Bennett",
  "Lucas Rivera",
  "Charlotte Kim",
  "Oliver Grant",
  "Amelia Scott",
  "Elijah Moore",
  "Harper Davis",
  "Henry Wells",
  "Evelyn Price",
  "Theo Martin",
  "Abigail Ross",
  "Leo Sullivan",
  "Ella James",
  "Jack Ellis",
];
const deals: [string, number, number, Stage, number][] = [
  ["Brand & website refresh", 0, 18500, "Proposal", 14],
  ["Service operations portal", 1, 24000, "Negotiation", 8],
  ["Spring retail launch", 2, 12800, "Qualified", 28],
  ["Client onboarding system", 3, 32000, "Proposal", 18],
  ["Project portfolio website", 4, 9500, "Lead", 35],
  ["Guest experience platform", 5, 45000, "Negotiation", 10],
  ["Field team workspace", 6, 28000, "Qualified", 24],
  ["E-commerce storefront", 7, 16500, "Proposal", 21],
  ["Lead generation website", 8, 14000, "Lead", 30],
  ["Agency resource hub", 9, 22000, "Qualified", 25],
  ["Coffee subscription shop", 10, 8800, "Won", -3],
  ["Customer success portal", 11, 38000, "Won", -7],
  ["Seasonal campaign landing page", 0, 6500, "Won", -38],
  ["Inventory dashboard", 2, 19500, "Lost", -4],
  ["Franchise discovery site", 5, 15000, "Lead", 40],
  ["Solar quote builder", 8, 26000, "Proposal", 17],
  ["Digital membership platform", 7, 21000, "Qualified", 32],
  ["Legacy system refresh", 11, 42000, "Lost", -12],
];
export function createSeed(now = new Date()): Workspace {
  const today = localDay(now),
    at = now.toISOString();
  const s: Workspace = {
    version: 1,
    firstLaunch: at,
    companies: companies.map(([name, industry, city], i) => ({
      id: `co-${i + 1}`,
      name,
      industry,
      city,
      website: `https://${name.toLowerCase().replace(/[^a-z]/g, "")}.example.com`,
      pinned: [0, 1, 5, 8].includes(i),
      createdAt: at,
      archived: false,
    })),
    contacts: people.map((name, i) => ({
      id: `ct-${i + 1}`,
      name,
      companyId: `co-${Math.floor(i / 2) + 1}`,
      email: `${name.toLowerCase().replace(" ", ".")}@example.com`,
      role: i % 2 ? "Operations manager" : "Founder",
      phone: `(555) 010-${String(1000 + i)}`,
      createdAt: at,
      archived: false,
    })),
    deals: deals.map(([name, co, amount, stage, offset], i) => ({
      id: `de-${i + 1}`,
      name,
      companyId: `co-${co + 1}`,
      contactId: `ct-${co * 2 + 1}`,
      amount,
      stage,
      expectedClose: addDays(today, offset),
      closedAt: ["Won", "Lost"].includes(stage) ? addDays(today, offset) : null,
      pinned: [0, 1, 5].includes(i),
      createdAt: at,
      archived: false,
    })),
    tasks: [],
    activities: [],
  };
  const titles = [
    "Send the revised proposal",
    "Follow up on project scope",
    "Share the launch timeline",
    "Confirm stakeholder feedback",
    "Schedule a discovery call",
    "Review the service agreement",
    "Send the technical overview",
    "Walk through the storefront",
    "Prepare discovery questions",
    "Check in on the resource hub",
    "Confirm kickoff details",
    "Share the handoff documents",
    "Request brand assets",
    "Close out opportunity",
    "Book an intro call",
    "Review quote requirements",
    "Send platform recommendations",
    "Record project feedback",
  ];
  s.tasks = deals.map((_, i) => ({
    id: `ta-${i + 1}`,
    title: titles[i],
    due: addDays(
      today,
      [-2, 0, 1, 0, 3, -1, 2, 4, 0, 5, 1, 2, -3, -1, 7, 3, 8, -5][i],
    ),
    priority: i % 3 === 0 ? "High" : i % 3 === 1 ? "Medium" : "Low",
    done: [10, 12, 13, 17].includes(i),
    completedAt: [10, 12, 13, 17].includes(i) ? at : null,
    record: { kind: "deal", id: `de-${i + 1}` },
    createdAt: at,
    archived: false,
  }));
  s.tasks.push(
    {
      id: "ta-19",
      title: "Reconnect with Olivia about the new direction",
      due: today,
      priority: "Medium",
      done: false,
      completedAt: null,
      record: { kind: "contact", id: "ct-1" },
      createdAt: at,
      archived: false,
    },
    {
      id: "ta-20",
      title: "Prepare next week’s prospect shortlist",
      due: addDays(today, 4),
      priority: "Low",
      done: false,
      completedAt: null,
      record: null,
      createdAt: at,
      archived: false,
    },
  );
  s.activities = s.deals.flatMap((d, i) => [
    {
      id: `ac-${i}-1`,
      record: { kind: "deal" as const, id: d.id },
      type: "created" as const,
      text: "Opportunity added to the pipeline.",
      at: new Date(now.valueOf() - (i + 5) * 86400000).toISOString(),
    },
    {
      id: `ac-${i}-2`,
      record: { kind: "deal" as const, id: d.id },
      type: i % 2 ? ("note" as const) : ("call" as const),
      text:
        i % 2
          ? "The team is reviewing the scope. Follow up with a clear next step."
          : "Discovery call completed. Discussed priorities, budget, and a realistic launch date.",
      at: new Date(now.valueOf() - ((i % 4) + 1) * 86400000).toISOString(),
    },
  ]);
  return s;
}
